package ar.edu.utn.frvm.typeit.boero_api.audit.enums;

public enum AuditAction {
  ENROLLMENT_APPLICATION_STARTED,
  ENROLLMENT_APPLICATION_DRAFT_UPDATED,
  ENROLLMENT_APPLICATION_SUBMITTED,
  ENROLLMENT_APPLICATION_CANCELLED,
  // Kept so events recorded before links required validation stay readable.
  GUARDIAN_DEPENDENT_LINKED,
  GUARDIAN_LINK_REQUESTED,
  GUARDIAN_LINK_APPROVED,
  GUARDIAN_LINK_REJECTED,
  GUARDIAN_DEPENDENT_UNLINKED
}
