package ar.edu.utn.frvm.typeit.boero_api.audit.enums;

public enum AuditAction {
  ENROLLMENT_APPLICATION_STARTED,
  ENROLLMENT_APPLICATION_DRAFT_UPDATED,
  ENROLLMENT_APPLICATION_SUBMITTED,
  ENROLLMENT_APPLICATION_CANCELLED,
  GUARDIAN_DEPENDENT_LINKED,
  GUARDIAN_DEPENDENT_UNLINKED
}
