package ar.edu.utn.frvm.typeit.boero_api.authorization.config;

import ar.edu.utn.frvm.typeit.boero_api.authorization.enums.PermissionCode;
import ar.edu.utn.frvm.typeit.boero_api.authorization.enums.SystemRoleCode;
import java.util.Map;
import java.util.Set;

public final class DefaultRolePermissions {
  private DefaultRolePermissions() {}

  private static final Map<SystemRoleCode, Set<PermissionCode>> INSTITUTIONAL =
      Map.of(
          SystemRoleCode.APPLICANT, Set.of(PermissionCode.ACADEMIC_OFFER_READ),
          SystemRoleCode.STUDENT,
              Set.of(PermissionCode.STUDY_PLAN_READ, PermissionCode.ACADEMIC_YEAR_READ),
          SystemRoleCode.ADMINISTRATIVE,
              Set.of(
                  PermissionCode.DOCUMENT_CATALOG_READ,
                  PermissionCode.ENROLLMENT_APPLICATION_READ,
                  PermissionCode.ENROLLMENT_DOCUMENT_REQUEST_CREATE,
                  PermissionCode.ENROLLMENT_ATTACHMENT_READ,
                  PermissionCode.ENROLLMENT_ATTACHMENT_UPLOAD,
                  PermissionCode.ENROLLMENT_ATTACHMENT_DELETE,
                  PermissionCode.ENROLLMENT_ATTACHMENT_REVIEW,
                  PermissionCode.ENROLLMENT_APPLICATION_APPROVE,
                  PermissionCode.ENROLLMENT_APPLICATION_REJECT,
                  PermissionCode.ENROLLMENT_APPLICATION_COURSE_READ,
                  PermissionCode.ENROLLMENT_APPLICATION_COURSE_ENROLL,
                  PermissionCode.ENROLLMENT_APPLICATION_COURSE_REJECT,
                  PermissionCode.COURSE_ENROLLMENT_READ,
                  PermissionCode.COURSE_ENROLLMENT_CREATE,
                  PermissionCode.COURSE_ENROLLMENT_WITHDRAW,
                  PermissionCode.COURSE_ENROLLMENT_ACADEMIC_STATUS_UPDATE,
                  PermissionCode.COURSE_WAITLIST_READ),
          SystemRoleCode.INSTITUTIONAL_AUTHORITY,
              Set.of(
                  PermissionCode.DOCUMENT_CATALOG_MANAGE,
                  PermissionCode.INSTITUTION_ROLE_ASSIGN,
                  PermissionCode.INSTITUTION_ROLE_REVOKE,
                  PermissionCode.INSTITUTION_PERSON_READ_ANY,
                  PermissionCode.INSTITUTION_PERSON_CREATE,
                  PermissionCode.INSTITUTION_PERSON_UPDATE_ANY,
                  PermissionCode.INSTITUTION_PERSON_DELETE,
                  PermissionCode.INSTITUTION_READ,
                  PermissionCode.INSTITUTION_UPDATE,
                  PermissionCode.ACADEMIC_YEAR_CREATE,
                  PermissionCode.ACADEMIC_YEAR_UPDATE,
                  PermissionCode.ACADEMIC_YEAR_STATUS_UPDATE,
                  PermissionCode.ACADEMIC_YEAR_DELETE,
                  PermissionCode.ACADEMIC_YEAR_RESTORE,
                  PermissionCode.TRAINING_PATH_CREATE,
                  PermissionCode.TRAINING_PATH_UPDATE,
                  PermissionCode.TRAINING_PATH_STATUS_UPDATE,
                  PermissionCode.TRAINING_PATH_DELETE,
                  PermissionCode.TRAINING_PATH_RESTORE,
                  PermissionCode.STUDY_PLAN_CREATE,
                  PermissionCode.STUDY_PLAN_UPDATE,
                  PermissionCode.STUDY_PLAN_STATUS_UPDATE,
                  PermissionCode.STUDY_PLAN_CURRICULUM_UPDATE,
                  PermissionCode.STUDY_PLAN_DELETE,
                  PermissionCode.STUDY_PLAN_RESTORE,
                  PermissionCode.ACADEMIC_OFFER_READ,
                  PermissionCode.ACADEMIC_SPACE_CREATE,
                  PermissionCode.ACADEMIC_SPACE_UPDATE,
                  PermissionCode.ACADEMIC_SPACE_STATUS_UPDATE,
                  PermissionCode.ACADEMIC_SPACE_DELETE,
                  PermissionCode.ACADEMIC_SPACE_RESTORE,
                  PermissionCode.INSTRUMENT_CREATE,
                  PermissionCode.INSTRUMENT_UPDATE,
                  PermissionCode.INSTRUMENT_STATUS_UPDATE,
                  PermissionCode.INSTRUMENT_DELETE,
                  PermissionCode.INSTRUMENT_RESTORE,
                  PermissionCode.ENROLLMENT_PERIOD_READ,
                  PermissionCode.ENROLLMENT_PERIOD_CREATE,
                  PermissionCode.ENROLLMENT_PERIOD_UPDATE,
                  PermissionCode.ENROLLMENT_PERIOD_STATUS_UPDATE,
                  PermissionCode.ENROLLMENT_PERIOD_DELETE,
                  PermissionCode.SHIFT_CREATE,
                  PermissionCode.SHIFT_UPDATE,
                  PermissionCode.SHIFT_STATUS_UPDATE,
                  PermissionCode.SHIFT_DELETE,
                  PermissionCode.SHIFT_RESTORE,
                  PermissionCode.COURSE_READ,
                  PermissionCode.COURSE_CREATE,
                  PermissionCode.COURSE_UPDATE,
                  PermissionCode.COURSE_STATUS_UPDATE,
                  PermissionCode.COURSE_DELETE,
                  PermissionCode.COURSE_RESTORE,
                  PermissionCode.DOCUMENT_CATALOG_READ,
                  PermissionCode.ENROLLMENT_APPLICATION_READ,
                  PermissionCode.ENROLLMENT_DOCUMENT_REQUEST_CREATE,
                  PermissionCode.ENROLLMENT_ATTACHMENT_READ,
                  PermissionCode.ENROLLMENT_ATTACHMENT_UPLOAD,
                  PermissionCode.ENROLLMENT_ATTACHMENT_DELETE,
                  PermissionCode.ENROLLMENT_ATTACHMENT_REVIEW,
                  PermissionCode.ENROLLMENT_APPLICATION_APPROVE,
                  PermissionCode.ENROLLMENT_APPLICATION_REJECT,
                  PermissionCode.ENROLLMENT_APPLICATION_COURSE_READ,
                  PermissionCode.ENROLLMENT_APPLICATION_COURSE_ENROLL,
                  PermissionCode.ENROLLMENT_APPLICATION_COURSE_REJECT,
                  PermissionCode.COURSE_ENROLLMENT_READ,
                  PermissionCode.COURSE_ENROLLMENT_CREATE,
                  PermissionCode.COURSE_ENROLLMENT_WITHDRAW,
                  PermissionCode.COURSE_ENROLLMENT_ACADEMIC_STATUS_UPDATE,
                  PermissionCode.COURSE_WAITLIST_READ));

  public static Set<PermissionCode> institutional(final SystemRoleCode role) {
    return INSTITUTIONAL.getOrDefault(role, Set.of());
  }
}
