spring.datasource.url=jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:boero_db}
spring.datasource.username=${DB_USER:boero}
spring.datasource.password=${DB_PASSWORD:boero}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6379}

logging.level.org.hibernate.SQL=DEBUG
