spring.datasource.url=jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:boero_db}
spring.datasource.username=${DB_USER:boero}
spring.datasource.password=${DB_PASSWORD:boero}
spring.datasource.driver-class-name=org.postgresql.Driver
