spring.datasource.url=jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:boero_db}
spring.datasource.username=${DB_USER:boero}
spring.datasource.password=${DB_PASSWORD:boero}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.sql.init.separator=@@
spring.jpa.defer-datasource-initialization=true
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6379}

logging.level.org.hibernate.SQL=DEBUG

app.jwt.secret=${JWT_SECRET:0123456789abcdef0123456789abcdef}

app.platform-admin.email=${PLATFORM_ADMIN_EMAIL:admin@plataforma.com}
app.platform-admin.password=${PLATFORM_ADMIN_PASSWORD:admin123}
app.platform-admin.name=${PLATFORM_ADMIN_NAME:Administrador}
app.platform-admin.last-name=${PLATFORM_ADMIN_LAST_NAME:Plataforma}

app.institutional-dev-user.institution-id=${INSTITUTIONAL_DEV_USER_INSTITUTION_ID:019e18e4-d919-76d8-9848-7f1b14e64452}
app.institutional-dev-user.document-number=${INSTITUTIONAL_DEV_USER_DOCUMENT_NUMBER:12345678}
app.institutional-dev-user.password=${INSTITUTIONAL_DEV_USER_PASSWORD:12345678}
app.institutional-dev-user.name=${INSTITUTIONAL_DEV_USER_NAME:Ana}
app.institutional-dev-user.last-name=${INSTITUTIONAL_DEV_USER_LAST_NAME:Garcia}
