CREATE TEMP TABLE seed_programs (code text PRIMARY KEY, name text NOT NULL, levels integer NOT NULL, source_url text NOT NULL) ON COMMIT DROP;
INSERT INTO seed_programs VALUES
    ('cavi', 'Ciclo Artístico Vocacional Infantil (CAVI)', 4, 'https://drive.google.com/file/d/1fpi_Iw6xdhQiLUTlX3ve3vFpHj7ck2SV/view'),
    ('cavb-instrumento', 'Ciclo Artístico Vocacional Básico en Instrumento (CAVB)', 3, 'https://drive.google.com/file/d/1HiTXgLejYh1w2qKY6mQiO0ydnVm9hU3a/view'),
    ('cavb-canto', 'Ciclo Artístico Vocacional Básico en Canto (CAVB)', 3, 'https://drive.google.com/file/d/1T9RU6Jx6SzgpPSzdIUdr9SMJID8tAAOw/view'),
    ('cava-instrumento', 'Ciclo Artístico Vocacional Avanzado en Instrumento (CAVA)', 3, 'https://drive.google.com/file/d/13mg8x7tln37Drm-XHDivA42BdhYtt0BE/view'),
    ('cava-canto', 'Ciclo Artístico Vocacional Avanzado en Canto (CAVA)', 3, 'https://drive.google.com/file/d/1zXgO0ad3gZvCfv9sOHCWAMZstVEyX_3-/view'),
    ('isfd', 'Profesorado de Música (ISFD)', 4, 'https://drive.google.com/file/d/1v1A8r6oZVr91GTyI8oT9OYd78ctylulB/view');

-- CAV names repeat by level, as in the forms; the curriculum placement carries the level.
-- ISFD harmonic guitar/piano rows are one curricular unit with two instrument options.
CREATE TEMP TABLE seed_curriculum (
    program text REFERENCES seed_programs, level integer, position integer,
    name text, type text, format text, instrument_group text,
    PRIMARY KEY (program, level, position)
) ON COMMIT DROP;
INSERT INTO seed_curriculum VALUES
    ('cavi', 1, 1, 'Lenguaje Musical', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cavi', 1, 2, 'Conjunto Vocal e Instrumental', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cavi', 1, 3, 'Instrumento', 'WORKSHOP', 'INDIVIDUAL', 'cav'),
    ('cavi', 2, 1, 'Lenguaje Musical', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cavi', 2, 2, 'Conjunto Vocal e Instrumental', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cavi', 2, 3, 'Instrumento', 'WORKSHOP', 'INDIVIDUAL', 'cav'),
    ('cavi', 3, 1, 'Lenguaje Musical', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cavi', 3, 2, 'Conjunto Vocal e Instrumental', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cavi', 3, 3, 'Instrumento', 'WORKSHOP', 'INDIVIDUAL', 'cav'),
    ('cavi', 4, 1, 'Lenguaje Musical', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cavi', 4, 2, 'Conjunto Vocal e Instrumental', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cavi', 4, 3, 'Instrumento', 'WORKSHOP', 'INDIVIDUAL', 'cav'),
    ('cavb-instrumento', 1, 1, 'Lenguaje Musical', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cavb-instrumento', 1, 2, 'Ensamble Vocal e Instrumental', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cavb-instrumento', 1, 3, 'Práctica Instrumental Individual', 'WORKSHOP', 'INDIVIDUAL', 'cav'),
    ('cavb-instrumento', 1, 4, 'Práctica Instrumental Grupal', 'WORKSHOP', 'GRUPAL', 'cav'),
    ('cavb-instrumento', 2, 1, 'Lenguaje Musical', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cavb-instrumento', 2, 2, 'Ensamble Vocal e Instrumental', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cavb-instrumento', 2, 3, 'Práctica Instrumental Individual', 'WORKSHOP', 'INDIVIDUAL', 'cav'),
    ('cavb-instrumento', 2, 4, 'Práctica Instrumental Grupal', 'WORKSHOP', 'GRUPAL', 'cav'),
    ('cavb-instrumento', 3, 1, 'Lenguaje Musical', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cavb-instrumento', 3, 2, 'Ensamble Vocal e Instrumental', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cavb-instrumento', 3, 3, 'Práctica Instrumental Individual', 'WORKSHOP', 'INDIVIDUAL', 'cav'),
    ('cavb-instrumento', 3, 4, 'Práctica Instrumental Grupal', 'WORKSHOP', 'GRUPAL', 'cav'),
    ('cavb-canto', 1, 1, 'Lenguaje Musical', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cavb-canto', 1, 2, 'Ensamble Vocal e Instrumental', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cavb-canto', 1, 3, 'Práctica de Canto Grupal', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cavb-canto', 1, 4, 'Práctica de Canto Individual', 'WORKSHOP', 'INDIVIDUAL', 'none'),
    ('cavb-canto', 2, 1, 'Lenguaje Musical', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cavb-canto', 2, 2, 'Ensamble Vocal e Instrumental', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cavb-canto', 2, 3, 'Práctica de Canto Grupal', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cavb-canto', 2, 4, 'Práctica de Canto Individual', 'WORKSHOP', 'INDIVIDUAL', 'none'),
    ('cavb-canto', 3, 1, 'Lenguaje Musical', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cavb-canto', 3, 2, 'Ensamble Vocal e Instrumental', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cavb-canto', 3, 3, 'Práctica de Canto Grupal', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cavb-canto', 3, 4, 'Práctica de Canto Individual', 'WORKSHOP', 'INDIVIDUAL', 'none'),
    ('cava-instrumento', 1, 1, 'Lenguaje y Apreciación Musical', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cava-instrumento', 1, 2, 'Ensamble de Música Argentina y Latinoamericana', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cava-instrumento', 1, 3, 'Instrumento Grupal', 'WORKSHOP', 'GRUPAL', 'cav'),
    ('cava-instrumento', 1, 4, 'Instrumento Individual', 'WORKSHOP', 'INDIVIDUAL', 'cav'),
    ('cava-instrumento', 2, 1, 'Lenguaje y Apreciación Musical', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cava-instrumento', 2, 2, 'Ensamble de Música Popular', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cava-instrumento', 2, 3, 'Instrumento Grupal', 'WORKSHOP', 'GRUPAL', 'cav'),
    ('cava-instrumento', 2, 4, 'Instrumento Individual', 'WORKSHOP', 'INDIVIDUAL', 'cav'),
    ('cava-instrumento', 3, 1, 'Lenguaje y Apreciación Musical', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cava-instrumento', 3, 2, 'Ensamble de Música de Cámara', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cava-instrumento', 3, 3, 'Instrumento Grupal', 'WORKSHOP', 'GRUPAL', 'cav'),
    ('cava-instrumento', 3, 4, 'Instrumento Individual', 'WORKSHOP', 'INDIVIDUAL', 'cav'),
    ('cava-canto', 1, 1, 'Lenguaje y Apreciación Musical', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cava-canto', 1, 2, 'Ensamble de Música Argentina y Latinoamericana', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cava-canto', 1, 3, 'Canto Grupal', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cava-canto', 1, 4, 'Canto Individual', 'WORKSHOP', 'INDIVIDUAL', 'none'),
    ('cava-canto', 2, 1, 'Lenguaje y Apreciación Musical', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cava-canto', 2, 2, 'Ensamble de Música Popular', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cava-canto', 2, 3, 'Canto Grupal', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cava-canto', 2, 4, 'Canto Individual', 'WORKSHOP', 'INDIVIDUAL', 'none'),
    ('cava-canto', 3, 1, 'Lenguaje y Apreciación Musical', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cava-canto', 3, 2, 'Ensamble de Música de Cámara', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cava-canto', 3, 3, 'Canto Grupal', 'WORKSHOP', 'GRUPAL', 'none'),
    ('cava-canto', 3, 4, 'Canto Individual', 'WORKSHOP', 'INDIVIDUAL', 'none'),
    ('isfd', 1, 1, 'Pedagogía', 'SUBJECT', 'GRUPAL', 'none'),
    ('isfd', 1, 2, 'Problemáticas Socioantropológicas en Educación', 'SUBJECT', 'GRUPAL', 'none'),
    ('isfd', 1, 3, 'Práctica Docente I', 'SEMINAR', 'GRUPAL', 'none'),
    ('isfd', 1, 4, 'Arte, Cultura y Sociedad', 'SEMINAR', 'GRUPAL', 'none'),
    ('isfd', 1, 5, 'Práctica y Teoría del Lenguaje Musical I', 'SUBJECT', 'GRUPAL', 'none'),
    ('isfd', 1, 6, 'Educación Vocal I', 'WORKSHOP', 'GRUPAL', 'none'),
    ('isfd', 1, 7, 'Práctica Coral I', 'WORKSHOP', 'GRUPAL', 'none'),
    ('isfd', 1, 8, 'Percusión Latinoamericana', 'WORKSHOP', 'GRUPAL', 'none'),
    ('isfd', 1, 9, 'Instrumento Armónico I', 'WORKSHOP', 'INDIVIDUAL', 'harmonic'),
    ('isfd', 1, 10, 'Música y Lenguaje Corporal', 'WORKSHOP', 'GRUPAL', 'none'),
    ('isfd', 2, 1, 'Didáctica General', 'SUBJECT', 'GRUPAL', 'none'),
    ('isfd', 2, 2, 'Psicología y Educación', 'SUBJECT', 'GRUPAL', 'none'),
    ('isfd', 2, 3, 'Práctica Docente II', 'SEMINAR', 'GRUPAL', 'none'),
    ('isfd', 2, 4, 'Sujetos de la Educación', 'SEMINAR', 'GRUPAL', 'none'),
    ('isfd', 2, 5, 'La Música en la Historia', 'SUBJECT', 'GRUPAL', 'none'),
    ('isfd', 2, 6, 'Práctica y Teoría del Lenguaje Musical II', 'SUBJECT', 'GRUPAL', 'none'),
    ('isfd', 2, 7, 'Educación Vocal II', 'WORKSHOP', 'GRUPAL', 'none'),
    ('isfd', 2, 8, 'Práctica Coral II', 'WORKSHOP', 'GRUPAL', 'none'),
    ('isfd', 2, 9, 'Instrumento Armónico II', 'WORKSHOP', 'INDIVIDUAL', 'harmonic'),
    ('isfd', 2, 10, 'Conjunto Instrumental I', 'WORKSHOP', 'GRUPAL', 'none'),
    ('isfd', 2, 11, 'Tecnología Analógica y Digital', 'WORKSHOP', 'GRUPAL', 'none'),
    ('isfd', 3, 1, 'Filosofía y Educación', 'SUBJECT', 'GRUPAL', 'none'),
    ('isfd', 3, 2, 'Práctica y Teoría del Lenguaje Musical III', 'SUBJECT', 'GRUPAL', 'none'),
    ('isfd', 3, 3, 'Práctica Docente III', 'SEMINAR', 'GRUPAL', 'none'),
    ('isfd', 3, 4, 'Educación Vocal y Práctica Coral III', 'WORKSHOP', 'GRUPAL', 'none'),
    ('isfd', 3, 5, 'Instrumento Armónico III', 'WORKSHOP', 'INDIVIDUAL', 'harmonic'),
    ('isfd', 3, 6, 'Conjunto Instrumental II', 'WORKSHOP', 'GRUPAL', 'none'),
    ('isfd', 3, 7, 'Folklore Argentino y Latinoamericano', 'WORKSHOP', 'GRUPAL', 'none'),
    ('isfd', 3, 8, 'Músicas Urbanas', 'SEMINAR', 'GRUPAL', 'none'),
    ('isfd', 3, 9, 'Didáctica de la Música en el Nivel Inicial y Primario', 'SUBJECT', 'GRUPAL', 'none'),
    ('isfd', 3, 10, 'UDI I - Taller Experimental de Didáctica Musical', 'WORKSHOP', 'GRUPAL', 'none'),
    ('isfd', 4, 1, 'Educación Sexual Integral', 'SEMINAR', 'GRUPAL', 'none'),
    ('isfd', 4, 2, 'Práctica Docente IV y Residencia', 'SEMINAR', 'GRUPAL', 'none'),
    ('isfd', 4, 3, 'Dirección Coral', 'WORKSHOP', 'GRUPAL', 'none'),
    ('isfd', 4, 4, 'Conjunto Instrumental III', 'WORKSHOP', 'GRUPAL', 'none'),
    ('isfd', 4, 5, 'El Arte en Educación Especial', 'SEMINAR', 'GRUPAL', 'none'),
    ('isfd', 4, 6, 'Investigación en Arte', 'SEMINAR', 'GRUPAL', 'none'),
    ('isfd', 4, 7, 'Producción Artística', 'WORKSHOP', 'GRUPAL', 'none'),
    ('isfd', 4, 8, 'Didáctica de la Música en el Nivel Secundario', 'SUBJECT', 'GRUPAL', 'none'),
    ('isfd', 4, 9, 'UDI II - Armonización y Arreglos del Repertorio Escolar', 'WORKSHOP', 'GRUPAL', 'none');
